### ISSUE TITLE
Compression Extensions

### ISSUE THREAD

**Issue by TheChifer** [fdimuccio/play2-sockjs#14]
Support Compression Ext for Play2 sockjs websockets, browser support is common

https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-20

**Comment by fdimuccio** [comment]
Unfortunately this issue cannot be dealt in Play2-SockJS because the websocket protocol relies on the underlying Play implementation, that is done with Netty. 

It seams that the compression ext has been added in netty-5.0.0.Alpha2, you can read more here [Add WebSocket compression](https://github.com/netty/netty/issues/1942) and here [Add WebSocket Extension handlers for client and server.](https://github.com/netty/netty/commit/282d6e73b82ec943a739201f7be1985c45ef032b). 

The bad news is that Play dependes on Netty 3.x and there is no plan to upgrade to 4 or 5, reference here [Upgrade to Netty 4](https://github.com/playframework/playframework/issues/2354).

Maybe you should report the issue to playframework devs.
