### ISSUE TITLE
Sockjs 0.9.x - Play2.9 Scala3 support

### ISSUE THREAD

**Issue by ProChirathF** [fdimuccio/play2-sockjs#41]
Play 2.9 supports Scala3, however Sockjs Play2.9 supported version, 0.9.0 supports only Scala 2.
Can you please release Sockjs 0.9.x with Scala 3 support

**Comment by mkurz** [comment]
Actually Sockjs 0.10.x (for Play 3) has support for Scala 3: https://repo1.maven.org/maven2/com/github/fdimuccio/play2-sockjs_3/

The reason why Sockjs 0.9.x does not have Scala 3 support is because akka-http 10.2.x (which is used in Play 2.9) also does not have Scala 3 artifacts, so Sockjs 0.9.x can not build with Scala 3.

@ProChirathF this means as soon as you upgrade to Play 3 and Sockjs 0.10.x you will have Sockjs 0.10.x Scala 3 support available.
